package cluster

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	goruntime "runtime"
	"strings"
	"sync"
	"time"

	"astrona/internal/config"
	"astrona/internal/ui"

	"gopkg.in/yaml.v3"
)

// ContainerEngine is whichever of Docker/Podman was found on PATH — kind
// needs to know which one to drive the local cluster with.
type ContainerEngine struct {
	Name string
	Path string
}

// DetectContainerEngine picks Docker or Podman — the first one installed
// that actually answers, so an installed-but-stopped Docker Desktop doesn't
// hide a running Podman. Checked once per run (per PATH). When none
// answers, the error says how to start one.
func DetectContainerEngine() (ContainerEngine, error) {
	engineCache.Lock()
	defer engineCache.Unlock()
	path := os.Getenv("PATH")
	if engineCache.done && engineCache.path == path {
		return engineCache.engine, engineCache.err
	}
	engineCache.engine, engineCache.err = detectContainerEngine()
	engineCache.path, engineCache.done = path, true
	return engineCache.engine, engineCache.err
}

var engineCache struct {
	sync.Mutex
	done   bool
	path   string
	engine ContainerEngine
	err    error
}

// engineInfoFormats is a cheap `info` per engine: it fails when the
// daemon (Docker) or machine (Podman on macOS/Windows) isn't running.
var engineInfoFormats = map[string]string{"docker": "{{.ServerVersion}}", "podman": "{{.Version.Version}}"}

func detectContainerEngine() (ContainerEngine, error) {
	var installed []ContainerEngine
	for _, name := range []string{"docker", "podman"} {
		if p, err := exec.LookPath(name); err == nil {
			installed = append(installed, ContainerEngine{Name: name, Path: p})
		}
	}
	if len(installed) == 0 {
		return ContainerEngine{}, fmt.Errorf("neither Docker nor Podman is installed — install one (https://docs.docker.com/get-docker/ or https://podman.io/docs/installation), then run `astrona check`")
	}
	for _, e := range installed {
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		err := exec.CommandContext(ctx, e.Path, "info", "--format", engineInfoFormats[e.Name]).Run()
		cancel()
		if err == nil {
			return e, nil
		}
	}
	return installed[0], fmt.Errorf("%s", engineNotRunning(installed))
}

// engineNotRunning says how to start the installed engine(s).
func engineNotRunning(installed []ContainerEngine) string {
	how := map[string]string{
		"docker": "start Docker Desktop (or the docker service)",
		"podman": "start it: podman machine start",
	}
	if goruntime.GOOS == "linux" {
		how["podman"] = "check `podman info`"
	}
	if len(installed) == 1 {
		name := map[string]string{"docker": "Docker", "podman": "Podman"}[installed[0].Name]
		return fmt.Sprintf("%s isn't running — %s", name, how[installed[0].Name])
	}
	return fmt.Sprintf("neither Docker nor Podman is running — %s, or %s", how["docker"], strings.TrimPrefix(how["podman"], "start it: "))
}

// kindClusterConfig is the subset of kind's own Cluster config
// (kind.x-k8s.io/v1alpha4) astrona generates from runtime.kind. Only
// fields with a typed counterpart in config.KindConfig exist here — see
// that type for why it's an allowlist.
type kindClusterConfig struct {
	Kind          string            `yaml:"kind"`
	APIVersion    string            `yaml:"apiVersion"`
	Nodes         []kindNode        `yaml:"nodes"`
	Networking    *kindNetworking   `yaml:"networking,omitempty"`
	FeatureGates  map[string]bool   `yaml:"featureGates,omitempty"`
	RuntimeConfig map[string]string `yaml:"runtimeConfig,omitempty"`
}

type kindNode struct {
	Role              string            `yaml:"role"`
	ExtraPortMappings []kindPortMapping `yaml:"extraPortMappings,omitempty"`
}

// kindPortMapping publishes a node container port on the host. Only ever
// generated by astrona itself (the gateway addon), always on 127.0.0.1 —
// never from lab config.
type kindPortMapping struct {
	ContainerPort int    `yaml:"containerPort"`
	HostPort      int    `yaml:"hostPort"`
	ListenAddress string `yaml:"listenAddress"`
	Protocol      string `yaml:"protocol"`
}

// GatewayNodePorts are the fixed NodePorts the gateway addon's Service
// uses (internal/addons) and kind maps to the host.
const (
	GatewayNodePortHTTP  = 30080
	GatewayNodePortHTTPS = 30443
)

type kindNetworking struct {
	DisableDefaultCNI bool   `yaml:"disableDefaultCNI,omitempty"`
	KubeProxyMode     string `yaml:"kubeProxyMode,omitempty"`
	IPFamily          string `yaml:"ipFamily,omitempty"`
	PodSubnet         string `yaml:"podSubnet,omitempty"`
	ServiceSubnet     string `yaml:"serviceSubnet,omitempty"`
}

// BuildKindConfig renders k as a kind cluster config file. Returns nil for
// a nil/empty k — the caller then runs `kind create cluster` without
// --config, exactly as before runtime.kind existed. The node image is not
// part of the file; it's passed as --image (applies to every node).
func BuildKindConfig(k *config.KindConfig) ([]byte, error) {
	if k.IsZero() {
		return nil, nil
	}

	cfg := kindClusterConfig{
		Kind:          "Cluster",
		APIVersion:    "kind.x-k8s.io/v1alpha4",
		FeatureGates:  k.FeatureGates,
		RuntimeConfig: k.RuntimeConfig,
	}
	for range k.ControlPlaneCount() {
		cfg.Nodes = append(cfg.Nodes, kindNode{Role: "control-plane"})
	}
	// A NodePort answers on every node, so mapping it on the first
	// control plane is enough.
	if a := k.Addons; a.GatewayAPI != "" && !a.SkipHostPorts {
		p := a.EffectiveGatewayPorts()
		cfg.Nodes[0].ExtraPortMappings = []kindPortMapping{
			{ContainerPort: GatewayNodePortHTTP, HostPort: p.HTTP, ListenAddress: "127.0.0.1", Protocol: "TCP"},
			{ContainerPort: GatewayNodePortHTTPS, HostPort: p.HTTPS, ListenAddress: "127.0.0.1", Protocol: "TCP"},
		}
	}
	for range k.WorkerCount() {
		cfg.Nodes = append(cfg.Nodes, kindNode{Role: "worker"})
	}
	if n := k.EffectiveNetworking(); n != (config.KindNetworking{}) {
		cfg.Networking = &kindNetworking{
			DisableDefaultCNI: n.DisableDefaultCNI,
			KubeProxyMode:     n.KubeProxyMode,
			IPFamily:          n.IPFamily,
			PodSubnet:         n.PodSubnet,
			ServiceSubnet:     n.ServiceSubnet,
		}
	}

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("failed to render kind cluster config: %w", err)
	}
	return out, nil
}

// kindCreateArgs builds `kind create cluster`'s argument slice.
// configPath is "" when no config file is used.
func kindCreateArgs(clusterName, configPath, nodeImage string) []string {
	args := []string{"create", "cluster", "--name", clusterName}
	if configPath != "" {
		args = append(args, "--config", configPath)
	}
	if nodeImage != "" {
		args = append(args, "--image", nodeImage)
	}
	return args
}

// writeKindConfig writes data to a private temp file for `kind create
// cluster --config`, returning its path and a cleanup func. No-op ("",
// no-op cleanup) for nil data.
func writeKindConfig(data []byte) (string, func(), error) {
	if data == nil {
		return "", func() {}, nil
	}
	f, err := os.CreateTemp("", "astrona-kind-config-*.yaml")
	if err != nil {
		return "", func() {}, fmt.Errorf("failed to create kind config file: %w", err)
	}
	cleanup := func() { os.Remove(f.Name()) }
	if _, err := f.Write(data); err != nil {
		f.Close()
		cleanup()
		return "", func() {}, fmt.Errorf("failed to write kind config file: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return "", func() {}, fmt.Errorf("failed to write kind config file: %w", err)
	}
	return f.Name(), cleanup, nil
}

// CreateKindCluster creates clusterName, shaped by k (runtime.kind; nil
// for kind's defaults).
func CreateKindCluster(clusterName string, k *config.KindConfig, rep *ui.Reporter) error {
	t := rep.Step("Detect container engine")
	engine, err := DetectContainerEngine()
	if err != nil {
		return t.Fail(err)
	}

	kindPath, err := exec.LookPath("kind")
	if err != nil {
		return t.Fail(fmt.Errorf("kind not found in PATH: %w", err))
	}
	t.Done()

	label := fmt.Sprintf("Create kind cluster %q (%s)", clusterName, engine.Name)
	if !k.IsZero() {
		label = fmt.Sprintf("Create kind cluster %q (%s; %s)", clusterName, engine.Name, k.Describe())
	}
	t = rep.Step("%s", label)

	data, err := BuildKindConfig(k)
	if err != nil {
		return t.Fail(err)
	}
	configPath, cleanup, err := writeKindConfig(data)
	if err != nil {
		return t.Fail(err)
	}
	defer cleanup()

	out := t.Output()
	if data != nil {
		fmt.Fprintf(out, "kind cluster config:\n%s\n", data)
	}

	cmd := exec.Command(kindPath, kindCreateArgs(clusterName, configPath, k.NodeImage())...)
	cmd.Stdout = out
	cmd.Stderr = out

	cmd.Env = os.Environ()
	if engine.Name == "podman" {
		cmd.Env = append(cmd.Env, "KIND_EXPERIMENTAL_PROVIDER=podman")
	}

	if err := cmd.Run(); err != nil {
		if img := k.NodeImage(); img != "" {
			return t.Fail(fmt.Errorf("%w (node image '%s' — check it exists and matches your kind version: https://github.com/kubernetes-sigs/kind/releases)", err, img))
		}
		return t.Fail(err)
	}
	t.Done()
	return nil
}

func DeleteKindCluster(clusterName string, rep *ui.Reporter) error {
	kindPath, err := exec.LookPath("kind")
	if err != nil {
		return fmt.Errorf("kind not found in PATH: %w", err)
	}

	t := rep.Step("Delete kind cluster %q", clusterName)

	cmd := exec.Command(kindPath, "delete", "cluster", "--name", clusterName)
	// Same provider selection as create: without it, kind falls back to
	// docker on a machine where docker is installed but only podman runs.
	cmd.Env = kindEnv()
	out := t.Output()
	cmd.Stdout = out
	cmd.Stderr = out

	if err := cmd.Run(); err != nil {
		return t.Fail(err)
	}
	if err := RemoveLabState(clusterName); err != nil {
		return t.Fail(err)
	}
	t.Done()
	return nil
}
