#!/usr/bin/env bash
# Prints the Homebrew formula for an astrona release, for the tap
# astrona-io/homebrew-tap (Formula/astrona.rb). Used by release.yml after
# the GitHub release is published:
#
#   .github/scripts/homebrew-formula.sh v0.3.0 dist/SHA256SUMS > astrona.rb
#
# The formula installs the same bare per-platform binaries `astrona upgrade`
# and the curl install use, pinned to the SHA-256 values in SHA256SUMS.
set -euo pipefail

tag="${1:?usage: homebrew-formula.sh <tag> <SHA256SUMS>}"
sums="${2:?usage: homebrew-formula.sh <tag> <SHA256SUMS>}"

if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "homebrew-formula.sh: '$tag' isn't a release tag (vX.Y.Z)" >&2
  exit 1
fi

sha() {
  local s
  s=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  if [[ ! "$s" =~ ^[0-9a-f]{64}$ ]]; then
    echo "homebrew-formula.sh: no SHA-256 for $1 in $sums" >&2
    exit 1
  fi
  echo "$s"
}

base="https://github.com/astrona-io/astrona-cli/releases/download/${tag}"
darwin_arm64=$(sha astrona-darwin-arm64)
darwin_amd64=$(sha astrona-darwin-amd64)
linux_arm64=$(sha astrona-linux-arm64)
linux_amd64=$(sha astrona-linux-amd64)

cat <<RUBY
# Generated by astrona-cli's release workflow (.github/scripts/homebrew-formula.sh)
# for ${tag} — don't edit by hand, the next release overwrites it.
class Astrona < Formula
  desc "Local Kubernetes (kind) and QEMU lab environments: run, grade, tear down"
  homepage "https://github.com/astrona-io/astrona-cli"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Required for every kind lab; Docker or Podman (also required) is left to
  # the user — see caveats. qemu, oras and git are only needed by some labs.
  depends_on "kind"
  depends_on "kubernetes-cli"

  on_macos do
    on_arm do
      url "${base}/astrona-darwin-arm64"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${base}/astrona-darwin-amd64"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/astrona-linux-arm64"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${base}/astrona-linux-amd64"
      sha256 "${linux_amd64}"
    end
  end

  def install
    # A bare download isn't executable yet, and astrona runs below to
    # generate its completions and man pages.
    binary = Dir["astrona-*"].first
    chmod 0755, binary
    bin.install binary => "astrona"
    generate_completions_from_executable(bin/"astrona", "completion")
    system bin/"astrona", "docgen", "--man", "--output", buildpath/"man"
    man1.install Dir[buildpath/"man/*.1"]
  end

  def caveats
    <<~EOS
      kind needs a container engine — Docker or Podman:
        brew install podman && podman machine init && podman machine start
      or Docker Desktop. \`astrona check\` lists anything else that's missing.

      Upgrade with \`brew upgrade astrona\` (\`astrona upgrade\` runs it for you).
      \`brew uninstall astrona\` leaves ~/.astrona (labs, results, approvals);
      destroy running labs first: astrona destroy <lab>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/astrona --version")
    assert_match "astrona-run", shell_output("man -P cat #{man1}/astrona-run.1")
    assert_match "__start_astrona", (bash_completion/"astrona").read
  end
end
RUBY
