#!/usr/bin/env bash
# Prints the Homebrew formula for an astrona release, for the tap
# astrona-io/homebrew-tap (Formula/astrona.rb). Used by release.yml after
# the GitHub release is published:
#
#   .github/scripts/homebrew-formula.sh v0.3.0 dist/SHA256SUMS > astrona.rb
#
# The formula installs the same bare per-platform binaries `astrona upgrade`
# and the curl install use, pinned to the SHA-256 values in SHA256SUMS.
set -euo pipefail

tag="${1:?usage: homebrew-formula.sh <tag> <SHA256SUMS>}"
sums="${2:?usage: homebrew-formula.sh <tag> <SHA256SUMS>}"

if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "homebrew-formula.sh: '$tag' isn't a release tag (vX.Y.Z)" >&2
  exit 1
fi

sha() {
  local s
  s=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  if [[ ! "$s" =~ ^[0-9a-f]{64}$ ]]; then
    echo "homebrew-formula.sh: no SHA-256 for $1 in $sums" >&2
    exit 1
  fi
  echo "$s"
}

base="https://github.com/astrona-io/astrona-cli/releases/download/${tag}"
darwin_arm64=$(sha astrona-darwin-arm64)
darwin_amd64=$(sha astrona-darwin-amd64)
linux_arm64=$(sha astrona-linux-arm64)
linux_amd64=$(sha astrona-linux-amd64)

cat <<RUBY
# Generated by astrona-cli's release workflow (.github/scripts/homebrew-formula.sh)
# for ${tag} — don't edit by hand, the next release overwrites it.
class Astrona < Formula
  desc "Local Kubernetes (kind) and QEMU lab environments: run, grade, tear down"
  homepage "https://github.com/astrona-io/astrona-cli"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/astrona-darwin-arm64"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${base}/astrona-darwin-amd64"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/astrona-linux-arm64"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${base}/astrona-linux-amd64"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install Dir["astrona-*"].first => "astrona"
  end

  def caveats
    <<~EOS
      astrona runs labs on kind with Docker or Podman, and uses kubectl;
      \`astrona check\` lists what's missing and how to install it.
      Upgrade with \`brew upgrade astrona\` (\`astrona upgrade\` runs it for you).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/astrona --version")
  end
end
RUBY
