package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"
)

// labRow is one line of `astrona list`'s output table — one qemu VM or one
// kind cluster, shaped the same way regardless of runtime so both print
// through the same tabwriter (the kubectl-get-style aligned-columns look
// this command is going for).
type labRow struct {
	name    string
	runtime string
	status  string
	uptime  string
	details string
}

// newListCmd builds `astrona list`. It lists every running qemu VM and kind
// cluster generated by astrona. It filters both runtimes by the "astro-"
// name prefix, ensuring only astrona-managed resources show up.
func newListCmd() *cobra.Command {
	return &cobra.Command{
		Use:          "list",
		Short:        "List astrona labs (qemu VMs and kind clusters) known on this machine",
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			rows, stale, err := collectQEMURows()
			if err != nil {
				return err
			}
			rows = append(rows, collectKindRows()...)

			printLabTable(rows)

			if stale > 0 {
				fmt.Printf("\n(%d stale qemu state dir(s) left behind by a VM that's no longer running — `astrona destroy -c <lab>` to clean up)\n", stale)
			}

			return nil
		},
	}
}

// printLabTable renders rows the way `kubectl get pods` renders resources:
// a header row plus one aligned row per lab, columns padded by tabwriter
// rather than hand-rolled Printf width specifiers (which drift as soon as a
// name is longer than the hardcoded width). Empty is reported the same way
// kubectl reports an empty list ("No resources found") instead of two
// separate "(none running)" sections per runtime.
func printLabTable(rows []labRow) {
	if len(rows) == 0 {
		fmt.Println("No astrona labs running.")
		return
	}

	w := tabwriter.NewWriter(os.Stdout, 0, 4, 3, ' ', 0)
	fmt.Fprintln(w, "NAME\tRUNTIME\tSTATUS\tUPTIME\tDETAILS")
	for _, r := range rows {
		fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", r.name, r.runtime, r.status, r.uptime, r.details)
	}
	w.Flush()
}

// collectQEMURows gathers a labRow for every live qemu VM found under
// ~/.astrona/qemu, and separately counts (without deleting) stale state dirs
// left behind by a VM that's no longer running — the state dir alone doesn't
// mean the VM is still up, LoadQEMUHandle's processAlive check is the only
// source of truth.
func collectQEMURows() ([]labRow, int, error) {
	base, err := qemuBaseDir()
	if err != nil {
		return nil, 0, err
	}

	entries, err := os.ReadDir(base)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to read qemu state dir '%s': %w", base, err)
	}

	var rows []labRow
	stale := 0

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}

		if !strings.HasPrefix(e.Name(), "astro-") {
			continue
		}

		data, err := os.ReadFile(filepath.Join(base, e.Name(), "handle.json"))
		if err != nil {
			continue
		}

		var h QEMUHandle
		if err := json.Unmarshal(data, &h); err != nil {
			continue
		}

		if !processAlive(h.PID) {
			stale++
			continue
		}

		uptime := "unknown"
		if !h.StartedAt.IsZero() {
			uptime = formatUptime(time.Since(h.StartedAt))
		}

		rows = append(rows, labRow{
			name:    h.ClusterName,
			runtime: "qemu",
			status:  "Running",
			uptime:  uptime,
			details: fmt.Sprintf("ssh %s@%s -p %d", h.SSHUser, h.SSHHost, h.SSHPort),
		})
	}

	return rows, stale, nil
}

// collectKindRows gathers a labRow for every astrona-generated kind cluster
// by querying the container engine directly for containers carrying kind's
// own "io.x-k8s.kind.cluster" label, rather than shelling out to `kind get
// clusters`. Deliberate: `kind get clusters` has a known bug against podman
// where its output template fails on podman's `ps` JSON shape (confirmed on
// this repo's own dev machine — "error calling index: cannot index
// slice/array with type string"), which would make this permanently broken
// on any podman-only host. kind always names a cluster's control-plane
// container "<cluster>-control-plane" regardless of provider, so filtering
// on the label and stripping that suffix gets the same answer without going
// through kind's broken path — and conveniently, `docker`/`podman inspect`
// on that same container name is exactly how uptime is derived too.
//
// Filtered to show only names starting with the "astro-" prefix, so only
// astrona-generated kind clusters are listed.
func collectKindRows() []labRow {
	engine, err := DetectContainerEngine()
	if err != nil {
		return nil
	}

	out, err := exec.Command(engine.Path, "ps", "-a",
		"--filter", "label=io.x-k8s.kind.cluster",
		"--format", "{{.Names}}").Output()
	if err != nil {
		return nil
	}

	var names []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if name, ok := strings.CutSuffix(strings.TrimSpace(line), "-control-plane"); ok && name != "" {
			if strings.HasPrefix(name, "astro-") {
				names = append(names, name)
			}
		}
	}

	rows := make([]labRow, 0, len(names))
	for _, name := range names {
		uptime := "unknown"
		if started, err := containerStartedAt(engine, name+"-control-plane"); err == nil {
			uptime = formatUptime(time.Since(started))
		}

		rows = append(rows, labRow{
			name:    name,
			runtime: "kind",
			status:  "Running",
			uptime:  uptime,
			details: "kubectl --context kind-" + name,
		})
	}

	return rows
}

// containerTimeLayouts covers both engines' `inspect -f '{{.State.StartedAt}}'`
// output: docker prints RFC3339Nano, podman prints Go's default
// time.Time.String() layout (e.g. "2026-08-11 21:14:17.140921448 +0200
// CEST") — different enough that one layout can't parse both.
var containerTimeLayouts = []string{
	time.RFC3339Nano,
	"2006-01-02 15:04:05.999999999 -0700 MST",
}

// containerStartedAt reads a container's start time via `docker`/`podman
// inspect` (same `-f`/Go-template syntax for both), used to derive a kind
// cluster's uptime from its control-plane container.
func containerStartedAt(engine ContainerEngine, containerName string) (time.Time, error) {
	out, err := exec.Command(engine.Path, "inspect", "-f", "{{.State.StartedAt}}", containerName).Output()
	if err != nil {
		return time.Time{}, fmt.Errorf("failed to inspect container '%s': %w", containerName, err)
	}

	trimmed := strings.TrimSpace(string(out))

	var lastErr error
	for _, layout := range containerTimeLayouts {
		if t, err := time.Parse(layout, trimmed); err == nil {
			return t, nil
		} else {
			lastErr = err
		}
	}

	return time.Time{}, fmt.Errorf("failed to parse container start time '%s': %w", trimmed, lastErr)
}

// formatUptime renders d as the coarsest human unit that fits (Xh Ym, Xm Ys,
// or Xs) — a VM's uptime doesn't need sub-second precision.
func formatUptime(d time.Duration) string {
	d = d.Round(time.Second)
	h := d / time.Hour
	d -= h * time.Hour
	m := d / time.Minute
	d -= m * time.Minute
	s := d / time.Second

	if h > 0 {
		return fmt.Sprintf("%dh%dm", h, m)
	}
	if m > 0 {
		return fmt.Sprintf("%dm%ds", m, s)
	}
	return fmt.Sprintf("%ds", s)
}
